# SPDX-License-Identifier: MIT
# winpodx debloat: disable noisy/unused scheduled tasks (sysguides list).
#
# Tasks targeted:
#   * Application Experience\Microsoft Compatibility Appraiser
#   * Autochk\Proxy
#   * Customer Experience Improvement Program\Consolidator + KernelCeipTask + UsbCeip
#   * DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector
#   * Maps\MapsToastTask + MapsUpdateTask
#   * RetailDemo\CleanupOfflineContent (deals with rentable demo content)
#   * Windows Error Reporting\QueueReporting

# $tasks = @(
#    "\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
#    "\Microsoft\Windows\Application Experience\ProgramDataUpdater",
#    "\Microsoft\Windows\Autochk\Proxy",
#    "\Microsoft\Windows\Customer Experience Improvement Program\Consolidator",
#    "\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask",
#    "\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip",
#    "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
#    "\Microsoft\Windows\Maps\MapsToastTask",
#    "\Microsoft\Windows\Maps\MapsUpdateTask",
#    "\Microsoft\Windows\RetailDemo\CleanupOfflineContent",
#    "\Microsoft\Windows\Windows Error Reporting\QueueReporting"
# )

$tasks = @(
	"\Microsoft\Windows\MemoryDiagnostic\CorruptionDetector",
	"\Microsoft\Windows\MemoryDiagnostic\DecompressionFailureDetector",
	"\Microsoft\Office\Office ClickToRun Service Monitor",
	"\Microsoft\Office\OfficeTelemetry\AgentFallBack2016",
	"\Microsoft\Office\OfficeTelemetry\OfficeTelemetryAgentLogOn2016",
	"\Microsoft\Office\OfficeTelemetryAgentFallBack2016",
	"\Microsoft\Office\OfficeTelemetryAgentLogOn2016",
	"\Microsoft\Office\OfficeTelemetryAgentFallBack",
	"\Microsoft\Office\OfficeTelemetryAgentLogOn",
	"\Microsoft\Office\Office 15 Subscription Heartbeat",
	"\Microsoft\Windows\Application Experience\AitAgent",
	"\Microsoft\Windows\NetTrace\GatherNetworkInfo",
	"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticResolver",
	"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
	"\Microsoft\Windows\Active Directory Rights Management Services Client\AD RMS Rights Policy Template Management (Automated)",
	"\Microsoft\Windows\AppID\EDP Policy Manager",
	"\Microsoft\Windows\AppID\PolicyConverter",
	"\Microsoft\Windows\Application Experience\MareBackup",
	"\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
	"\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser Exp",
	"\Microsoft\Windows\Application Experience\PcaPatchDbTask",
	"\Microsoft\Windows\Application Experience\SdbinstMergeDbTask",
	"\Microsoft\Windows\Application Experience\StartupAppTask",
	"\Microsoft\Windows\Application Experience\ProgramDataUpdater",
	"\Microsoft\Windows\Application Experience\ProgramInventoryUpdater",
	"\Microsoft\Windows\ApplicationData\appuriverifierdaily",
	"\Microsoft\Windows\ApplicationData\appuriverifierinstall",
	"\Microsoft\Windows\ApplicationData\DsSvcCleanup",
	"\Microsoft\Windows\AppxDeploymentClient\Pre-staged app cleanup",
	"\Microsoft\Windows\AppxDeploymentClient\UCPD velocity",
	"\Microsoft\Windows\Autochk\Proxy",
	"\Microsoft\Windows\AutoLogger\AutoLogger-Diagtrack-Listener",
	"\Microsoft\Windows\AutoLogger\AutoLogger-FileSizeTracking",
	"\Microsoft\Windows\BrokerInfrastructure\BgTaskRegistrationMaintenanceTask",
	"\Microsoft\Windows\CEIP\Uploader",
	"\Microsoft\Windows\CertificateServicesClient\AikCertEnrollTask",
	"\Microsoft\Windows\CertificateServicesClient\CryptoPolicyTask",
	"\Microsoft\Windows\CertificateServicesClient\KeyPreGenTask",
	"\Microsoft\Windows\CertificateServicesClient\SystemTask",
	"\Microsoft\Windows\Cleanup\UpdateCleanup",
	"\Microsoft\Windows\Clip\License Validation",
	"\Microsoft\Windows\Clip\LicenseImdsIntegration",
	"\Microsoft\Windows\CloudExperienceHost\CreateObjectTask",
	"\Microsoft\Windows\CloudExperienceHost\SyncHost",
	"\Microsoft\Windows\CloudRestore\Backup",
	"\Microsoft\Windows\CloudRestore\Restore",
	"\Microsoft\Windows\ContactSupport\Scheduled",
	"\Microsoft\Windows\Customer Experience Improvement Program\Consolidator",
	"\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask",
	"\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip",
	"\Microsoft\Windows\Customer Experience Improvement Program\BthSQM",
	"\Microsoft\Windows\Customer Experience Improvement Program\Uploader",
	"\Microsoft\Windows\Device Information\Device",
	"\Microsoft\Windows\Device Information\Device User",
	"\Microsoft\Windows\Device Setup\Driver Recovery on Reboot",
	"\Microsoft\Windows\Device Setup\Metadata Refresh",
	"\Microsoft\Windows\DeviceDirectoryClient\HandleCommand",
	"\Microsoft\Windows\DeviceDirectoryClient\HandleWnsCommand",
	"\Microsoft\Windows\DeviceDirectoryClient\IntegrityCheck",
	"\Microsoft\Windows\DeviceDirectoryClient\LocateCommandUserSession",
	"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceAccountChange",
	"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceLocationRightsChange",
	"\Microsoft\Windows\DeviceDirectoryClient\RegisterDevicePeriodic24",
	"\Microsoft\Windows\DeviceDirectoryClient\RegisterDevicePolicyChange",
	"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceProtectionStateChanged",
	"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceSettingChange",
	"\Microsoft\Windows\DeviceDirectoryClient\RegisterUserDevice",
	"\Microsoft\Windows\Diagnosis\RecommendedTroubleshootingScanner",
	"\Microsoft\Windows\Diagnosis\Scheduled",
	"\Microsoft\Windows\Diagnosis\UnexpectedCodepath",
	"\Microsoft\Windows\DiskCleanup\SilentCleanup",
	"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
	"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticResolver",
	"\Microsoft\Windows\DiskDiagnostic\DiagnosticResolver",
	"\Microsoft\Windows\DiskDiagnostic\DiskDiagnostic",
	"\Microsoft\Windows\DiskFootprint\Diagnostics",
	"\Microsoft\Windows\DiskFootprint\StorageSense",
	"\Microsoft\Windows\DUSM\dusmtask",
	"\Microsoft\Windows\ErrorReporting\QueueReporting",
	"\Microsoft\Windows\ErrorReporting\KernelCeipTask",
	"\Microsoft\Windows\ExploitGuard\ExploitGuard MDM policy Refresh",
	"\Microsoft\Windows\Feedback\Siuf\DmClient",
	"\Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload",
	"\Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioUpload",
	"\Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioRun",
	"\Microsoft\Windows\Feedback\Siuf\DmClientOnUserSignIn",
	"\Microsoft\Windows\File Classification Infrastructure\Property Definition Sync",
	"\Microsoft\Windows\FileHistory\File History (maintenance mode)",
	"\Microsoft\Windows\Help\OEMSupport",
	"\Microsoft\Windows\Help\WindowsHelpUpdateTask",
	"\Microsoft\Windows\HelloFace\FODCleanupTask",
	"\Microsoft\Windows\HelloFace\FeatureCleanup",
	"\Microsoft\Windows\input\InputSettingsRestoreDataAvailable",
	"\Microsoft\Windows\input\LocalUserSyncDataAvailable",
	"\Microsoft\Windows\input\MouseSyncDataAvailable",
	"\Microsoft\Windows\input\PenSyncDataAvailable",
	"\Microsoft\Windows\input\RemoteMouseSyncDataAvailable",
	"\Microsoft\Windows\input\RemotePenSyncDataAvailable",
	"\Microsoft\Windows\input\RemoteTouchpadSyncDataAvailable",
	"\Microsoft\Windows\input\TouchpadSyncDataAvailable",
	"\Microsoft\Windows\InstallService\WakeUpAndContinueUpdates",
	"\Microsoft\Windows\InstallService\WakeUpAndScanForUpdates",
	"\Microsoft\Windows\International\Synchronize Language Settings",
	"\Microsoft\Windows\LanguageComponentsInstaller\Installation",
	"\Microsoft\Windows\LanguageComponentsInstaller\ReconcileLanguageResources",
	"\Microsoft\Windows\LanguageComponentsInstaller\Uninstallation",
	"\Microsoft\Windows\License Manager\TempSignedLicenseExchange",
	"\Microsoft\Windows\Location\WindowsActionDialog",
	"\Microsoft\Windows\Maintenance\WinSAT",
	"\Microsoft\Windows\Maps\MapsToastTask",
	"\Microsoft\Windows\Maps\MapsUpdateTask",
	"\Microsoft\Windows\MemoryDiagnostic\AutomaticOfflineMemoryDiagnostic",
	"\Microsoft\Windows\MemoryDiagnostic\RunFullMemoryDiagnostic",
	"\Microsoft\Windows\NlaSvc\WiFiTask",
	"\Microsoft\Windows\Offline Files\Background Synchronization",
	"\Microsoft\Windows\Offline Files\Logon Synchronization",
	"\Microsoft\Windows\PCRPF\PCR Prediction Framework Firmware Update Task",
	"\Microsoft\Windows\PerformanceTrace\WhesvcToast",
	"\Microsoft\Windows\PI\Secure-Boot-Update",
	"\Microsoft\Windows\PI\Sqm-Tasks",
	"\Microsoft\Windows\Pluton\Pluton-Ksp-Provisioning",
	"\Microsoft\Windows\Power Efficiency Diagnostics\AnalyzeSystem",
	"\Microsoft\Windows\Printing\EduPrintProv",
	"\Microsoft\Windows\Printing\PrintJobCleanupTask",
	"\Microsoft\Windows\PushToInstall\LoginCheck",
	"\Microsoft\Windows\PushToInstall\Registration",
	"\Microsoft\Windows\Ras\MobilityManager",
	"\Microsoft\Windows\ReFsDedupSvc\Initialization",
	"\Microsoft\Windows\Registry\RegIdleBackup",
	"\Microsoft\Windows\RemoteAssistance\RemoteAssistanceTask",
	"\Microsoft\Windows\RetailDemo\CleanupOfflineContent",
	"\Microsoft\Windows\Search\IndexerDiagnosticsTask",
	"\Microsoft\Windows\Search\SearchIndexerMaintenance",
	"\Microsoft\Windows\Setup\SetupCleanupTask",
	"\Microsoft\Windows\SharedPC\Account Cleanup",
	"\Microsoft\Windows\Shell\FamilySafetyMonitor",
	"\Microsoft\Windows\Shell\FamilySafetyRefreshTask",
	"\Microsoft\Windows\Shell\IndexerAutomaticMaintenance",
	"\Microsoft\Windows\Shell\ThemeAssetTask_SyncFODState",
	"\Microsoft\Windows\Shell\ThemesSyncedImageDownload",
	"\Microsoft\Windows\Shell\UndockedFlightingUpdate",
	"\Microsoft\Windows\Shell\UpdateUserPictureTask",
	"\Microsoft\Windows\Storage Tiers Management\Storage Tiers Optimization",
	"\Microsoft\Windows\Subscription\EnableLicenseAcquisition",
	"\Microsoft\Windows\Subscription\LicenseAcquisition",
	"\Microsoft\Windows\Sysmain\WsSwapAssessmentTask",
	"\Microsoft\Windows\Sysmain\HybridDriveCacheRebalance",
	"\Microsoft\Windows\Sysmain\HybridDriveCachePrepopulate",
	"\Microsoft\Windows\UPnP\UPnPHostConfig",
	"\Microsoft\Windows\UpdateOrchestrator\CleanupUpdateTask",
	"\Microsoft\Windows\User Profile Service\HiveUploadTask",
	"\Microsoft\Windows\WaaSMedic\PerformRemediation",
	"\Microsoft\Windows\WaaSMedic\ScanForUpdates",
	"\Microsoft\Windows\WaaSMedic\WsusScan",
	"\Microsoft\Windows\Windows Error Reporting\QueueReporting",
	"\Microsoft\Windows\Windows Error Reporting\ReportQueue",
	"\Microsoft\Windows\Windows Filtering Platform\BfeOnServiceStartTypeChange",
	"\Microsoft\Windows\WindowsAI\Recall\InitialConfiguration",
	"\Microsoft\Windows\WindowsAI\Recall\PolicyConfiguration",
	"\Microsoft\Windows\WindowsAI\Settings\InitialConfiguration",
	"\Microsoft\Windows\WindowsAI\Copilot\CopilotDataCollectionTask",
	"\Microsoft\Windows\WindowsAI\Insights\InsightsDataCollectionTask",
	"\Microsoft\Windows\WindowsUpdate\Refresh Group Policy Cache",
	"\Microsoft\Windows\WlanSvc\CDSSync",
	"\Microsoft\Windows\WOF\WIM-Hash-Management",
	"\Microsoft\Windows\WOF\WIM-Hash-Validation",
	"\Microsoft\Windows\Workplace Join\Automatic-Device-Join",
	"\Microsoft\Windows\Workplace Join\Device-Sync",
	"\Microsoft\Windows\Workplace Join\Recovery-Check",
	"\Microsoft\Windows\UNP\RunCampaignManager",
	"\MicrosoftEdgeUpdateTaskMachineCore",
	"\MicrosoftEdgeUpdateTaskMachineUA",
	"\Microsoft\Windows\Windows Defender\Windows Defender Cache Maintenance",
	"\Microsoft\Windows\Windows Defender Cleanup",
	"\Microsoft\Windows\Windows Defender Scheduled Scan",
	"\Microsoft\Windows\Windows Defender Verification"
)

foreach ($task in $tasks) {
    Write-Host "[scheduled_tasks] Disabling $task"
    schtasks /Change /TN $task /Disable 2>$null | Out-Null
}
